{{- if and .Values.otelCollector.enabled .Values.otelCollector.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "nsangusa.fullname" . }}-otel
  labels:
    {{- include "nsangusa.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, watch]
  - apiGroups: [apps]
    resources: [deployments, replicasets]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nsangusa.fullname" . }}-otel
  labels:
    {{- include "nsangusa.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nsangusa.otelServiceAccount" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "nsangusa.fullname" . }}-otel
{{- end }}
