{{- if .Values.backend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nsangusa.backendServiceAccount" . }}
  labels:
    {{- include "nsangusa.labels" . | nindent 4 }}
  {{- with .Values.backend.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.backend.serviceAccount.annotations | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
---
{{- end }}
{{- if .Values.frontend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nsangusa.frontendServiceAccount" . }}
  labels:
    {{- include "nsangusa.labels" . | nindent 4 }}
  {{- with .Values.frontend.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.frontend.serviceAccount.annotations | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- if .Values.otelCollector.enabled }}
---
{{- end }}
{{- end }}
{{- if and .Values.otelCollector.enabled .Values.otelCollector.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nsangusa.otelServiceAccount" . }}
  labels:
    {{- include "nsangusa.labels" . | nindent 4 }}
  {{- with .Values.otelCollector.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.otelCollector.serviceAccount.annotations | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
