apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsangusa.fullname" . }}-backend
  labels:
    {{- include "nsangusa.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    {{- include "nsangusa.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      appProtocol: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsangusa.fullname" . }}-frontend
  labels:
    {{- include "nsangusa.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "nsangusa.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      appProtocol: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
