node-name: nsangusa-staging-1
node-ip: "164.132.42.235"
advertise-address: "164.132.42.235"
bind-address: "164.132.42.235"
https-listen-port: 6443
tls-san-security: true
write-kubeconfig-mode: "0600"

cluster-cidr: "10.42.0.0/16"
service-cidr: "10.43.0.0/16"
cluster-dns: "10.43.0.10"
cluster-domain: cluster.local
service-node-port-range: "30000-32767"
flannel-backend: host-gw
flannel-iface: ens3
egress-selector-mode: agent

disable:
  - traefik
  - servicelb
disable-network-policy: false
secrets-encryption: true
secrets-encryption-provider: aescbc

kube-proxy-arg:
  - proxy-mode=iptables
  - nodeport-addresses=127.0.0.0/8
  - iptables-localhost-nodeports=true
  - healthz-bind-address=127.0.0.1:10256
  - metrics-bind-address=127.0.0.1:10249

kubelet-arg:
  - read-only-port=0
  - max-pods=40
  - system-reserved=cpu=1000m,memory=2Gi
  - kube-reserved=cpu=500m,memory=1Gi
  - eviction-hard=memory.available<1Gi,nodefs.available<15%,imagefs.available<15%,nodefs.inodesFree<5%

kube-apiserver-arg:
  - audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log
  - audit-policy-file=/etc/nsangusa-k3s/audit-policy.yaml
  - audit-log-maxage=7
  - audit-log-maxbackup=5
  - audit-log-maxsize=10
  - service-account-extend-token-expiration=false
