apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: server-ingress
  namespace: nsangusa-k3s-qualification
spec:
  podSelector:
    matchLabels:
      app: qualification-server
  policyTypes: [Ingress]
  ingress: []
