global:
  environment: development

backendConfig:
  SPRING_PROFILES_ACTIVE: local
  PROVIDER_MODE: fake
  COOKIE_SECURE: "false"

backend:
  replicaCount: 1
  autoscaling:
    enabled: false
  pdb:
    enabled: false

frontend:
  replicaCount: 1
  autoscaling:
    enabled: false
  pdb:
    enabled: false

ingress:
  enabled: false
